version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    tty: true
    volumes:
      - ./utils/apache:/etc/apache2/sites-enabled
      - ./project:/var/www
  db:
    container_name: db
    image: mariadb:10.5.8
    restart: always
    volumes:
      - ./var/db-data:/var/lib/mysql
      #- ./utils/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      TZ: Europe/Paris
  phpmyadmin:
    container_name: pma
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
